Akademetre/Models/Session/Helpers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Akademetre.Models.Session
{
    public class Helpers
    {
        Dictionary<string, User> user = null;
        public Helpers()
        {
            user = new Dictionary<string, User>();
        }
        public List<User> UserList { get => user.Values.ToList(); }

        public void Add(User item)
        {

            user.Add(item.Email, item);
        }
    }
}

Akademetre/Models/Session/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Akademetre.Models.Session
{
    public class User
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
    }
}

Akademetre/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Akademetre.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Akademetre/Controllers/UserController.cs
using Akademetre.Models.Session;
using ClosedXML.Excel;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Compilation;
using System.Web.Mvc;

namespace Akademetre.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return View();
            }
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(string name, string surname, string adress, string email)
        {
            User user = new User();
            user.Name = name;
            user.Surname = surname;
            user.Adress = adress;
            user.Email = email;

            List<User> list = Session["users"] == null ? new List<User>() : Session["users"] as List<User>;
            list.Add(user);
            Session.Add("users", list);



            return RedirectToAction("Index");
        }
        [HttpPost]
        public FileResult Donwload()
        {
            DataTable dt = new DataTable("Users");
            dt.Columns.AddRange(new DataColumn[4]
            {
                new DataColumn("Name"),
                new DataColumn("Surname"),
                new DataColumn("Adress"),
                new DataColumn("Email")
            });

            
            foreach (var item in (List<User>)Session["users"])
            {
                dt.Rows.Add(item.Name, item.Surname, item.Adress, item.Email);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream=new MemoryStream())
                {
                    wb.SaveAs(stream);
                     return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Users.xlsx");
                }
            }

           
        }




    }
}

Akademetre/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Akademetre/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Akademetre/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Akademetre/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
*<body>
    @*
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>*@
    <div class="container body-content">
        @RenderBody()
        @*<hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/UserPost.js"></script>
    <script src="~/Scripts/site.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Akademetre/Views/User/Add.cshtml
@{
    ViewBag.Title = "Add";
}

    <form method="post">
        <label>Name</label>
        <input id="name" type="text" name="Name" value="" required />
        <label>Surname</label>
        <input id="surname" type="text" name="Surname" value="" required/>
        <label>Adress</label>
        <input id="adress" type="text" name="Adress" value="" required/>
        <label>Email</label>
        <input id="name" type="email" name="Email" value="" required/>

        <div>
            <button type="submit" class="btn btn-success">Confirm</button>
        </div>
    </form>

Akademetre/Views/User/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<Akademetre.Models.Session.User> list = (List<Akademetre.Models.Session.User>)Session["users"];
}

<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Surname</th>
                <th>Adress</th>
                <th>Email</th>
            </tr>
            
        </thead>
        <tbody>
            @if (list != null)
            {
                foreach (var item in list)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Surname</td>
                        <td>@item.Adress</td>
                        <td>@item.Email</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<div>
    <a href="/User/Add/" class="btn btn-primary">Add New</a>
</div>
<div class="form-group pull-right">
    @using (Html.BeginForm("Donwload", "User", FormMethod.Post))
    {
        if (list!=null)
        {
            <input type="submit" value="Dowload" class="btn btn-success" />
        }

    }
</div>